web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, :controllers => { :invitations => 'invitations' }
  resources :users

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss' => 'rss#rss'
  get '/atom' => 'rss#atom'
end

web-app/app/models/user.rb
class User < ApplicationRecord
	include TheRole::Api::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable
  validates :name, presence: true, length: { minimum: 2 }
end

web-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :role_required # проверяет роль юзера
  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path
  		flash[:success] = "Пользователь успешно зарегистрирован."
  	else
  		render "new"
  		flash[:danger] = "Ошибка."
  	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to root_path
  		flash[:success] = "Пользователь успешно обновлен."
  	else
  		render "edit"
  		flash[:danger] = "Ошибка."
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy

  	redirect_to root_path
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :role_id)
  end
end

web-app/app/helpers/users_helper.rb
module UsersHelper
end

web-app/app/views/users/_form.html.erb
<div class="row">
	<div class="col-sm-4">
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
				<%= f.hidden_field :role_id, value: 2 %>
			</div>

			<div class="form-group">
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.submit "Done", class: "btn btn-md btn-success" %>
			</div>
		<% end %>
	</div>
</div>

web-app/app/views/users/edit.html.erb
<h1 class="page-header">Edit <%= @user.name %></h1>

<%= render "form" %>

web-app/app/views/users/index.html.erb
<h1 class="page-header text-center">All users</h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Actions</th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= link_to "Edit", edit_user_path(user.id) %>
					<%= link_to "Delete", user_path(user.id), method: "delete" %>
			</td>
		</tr>
	<% end %>
</table>

web-app/app/views/users/new.html.erb
<h1>Create new user</h1>

<%= render "form" %>

web-app/app/views/users/show.html.erb
<h1><%= @user.name %></h1>