web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, :controllers => { :invitations => 'invitations' }
  resources :users

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss' => 'rss#rss'
  get '/atom' => 'rss#atom'
end

web-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TheRole::Controller
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def role_access_denied
    access_denied_method = TheRole.config.access_denied_method
    return send(access_denied_method) if access_denied_method && respond_to?(access_denied_method)
    the_role_default_access_denied_response
  end

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name, :role_id])
  end

	def the_role_default_access_denied_response
    access_denied_msg = t(:access_denied, scope: :the_role)

    if request.xhr?
      render json: {
        errors: { the_role: [ access_denied_msg ] },

        controller_name:      controller_path,
        action_name:          action_name,
        has_access_to_action: current_user.try(:has_role?, controller_path, action_name),

        current_user: { id: current_user.try(:id) }

        # owner_check_object: {
        #   owner_check_object_id:    @owner_check_object.try(:id),
        #   owner_check_object_class: @owner_check_object.try(:class).try(:to_s)
        # },

        # has_access_to_object: current_user.try(:owner?, @owner_check_object)
      }, status: 401
    else
      # When the user paste non authorized URL in browser the REFERER is blank and application crash
      if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        # redirect_to root_path, flash: { error: access_denied_msg }
        render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
      else
      	render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
        # redirect_to root_path, flash: { error: access_denied_msg }
      end
    end
  end
end

web-app/app/helpers/application_helper.rb
module ApplicationHelper
end

web-app/app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyCity", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Действия<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Категории", categories_path %></li>
          <li><%= link_to "Сообщения", messages_path %></li>
          <li>
            <%= link_to 'Админ панель',  admin_roles_path if current_user && current_user.admin? %>
          </li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Регистрация", new_user_invitation_path if current_user && current_user.admin? %></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right" id="user_actions">
      <li><%= link_to 'Выход', destroy_user_session_path if current_user %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Все", root_path %></li>
      <li><%= link_to "Ожидают модерации", messages_path(status: :new_message) %></li>
      <li><%= link_to "Выполненные", messages_path(status: :done) %></li>
      <li><%= link_to "Актуальные", messages_path(status: :actual) %></li>
      <li><%= link_to "Неактуальные", messages_path(status: :not_relevant) %></li>
      <li style="visibility: hidden;">Divider</li>
    </ul>
  </div>
</nav>