web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, :controllers => { :invitations => 'invitations' }
  resources :users

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss' => 'rss#rss'
  get '/atom' => 'rss#atom'
end

web-app/app/models/message.rb
class Message < ApplicationRecord

	enum status: [ :for_moderation, :done, :actual, :not_relevant, :hidden ]

	has_many :images, dependent: :destroy
	belongs_to :category

	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude

	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	after_validation :reverse_geocode, if: ->(obj){ obj.latitude.present? and obj.longitude.present? and obj.address.nil? }

    paginates_per 10

end

web-app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:update, :show, :edit, :archiving]
  before_action :role_required, except: [:create, :image_save]  # проверяет роль юзера
  skip_before_action :authenticate_user!, only: [:create, :image_save]

  def index
    if params[:status].nil?
      @messages = Message.all.where.not(status: :hidden).order(created_at: :desc).order(:body).page(params[:page])
      @title = "Все сообщения"
    else
      @messages = Message.all.where(status: params[:status]).order(created_at: :desc).order(:body).page(params[:page])
      @title =
      case params[:status]
      when "new_message"
        "Новые сообщения"
      when "done"
        "Выполненные сообщения"
      when "actual"
        "Актуальные сообщения"
      when "not_relevant"
        "Неактуальные сообщения"
      end
    end
  end

  def create
    @message = Message.create(message_params)
    render plain: @message.id
  end

  def image_save
    Image.create(image: params[:image], message_id: params[:message_id])
  end

  def show
    @hash = Gmaps4rails.build_markers(@message) do |message, marker|
      marker.lat message.latitude
      marker.lng message.longitude
      marker.infowindow message.address
    end
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    if @message.update(message_params)
      redirect_back(fallback_location: root_path)
      flash[:success] = "Статус сообщения успешно изменен!"
    else
      render 'edit'
    end
  end

  def archiving
    @message.status = "hidden"
    @message.save
    flash[:success] = "Сообщение успешно удалено!"
    redirect_to root_path
  end

  private
  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:body, :latitude, :longitude, :address, :status, :category_id)
  end

  def image_params
    params.require(:image).permit({image: []})
  end

end

web-app/app/helpers/messages_helper.rb
module MessagesHelper
	def panel_type(message)
		panel_type =
			case message.status
			when "new_message"
				"info"
			when "actual"
				"warning"
			when "done"
				"success"
			when "not_relevant"
				"default"
			else
				"primary"
			end
	end

end

web-app/app/views/messages/_change_category.html.erb
<%= form_for message, url: message_path(message) do |f| %>
	<div class="col-md-6">
		<%= f.collection_select :category_id, Category.all, :id, :title %>
		<br />
		<br />
		<%= f.submit 'Обновить категорию', class: 'btn btn-primary btn-xs' %>
	</div>
<% end %>

web-app/app/views/messages/_change_status.html.erb
<%= form_for message, url: message_path(message) do |f| %>
	<div class="col-md-6">
	<%= f.select(:status,
							options_for_select([['На модерацию', message.status = 'for_moderation'],
																	['Выполнено', message.status = 'done'],
																	['Актуально', message.status = 'actual'],
																	['Не релевантно', message.status = 'not_relevant']])
							) %>
	</div>
	<div class="col-md-6">
	<%= f.submit 'Обновить статус', class: 'btn btn-primary btn-xs' %>
	</div><br>
<% end %>

web-app/app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
	<%= f.input :body,label: "Текст" %>
	<%= f.input :category_id, label: "Категория", collection: Category.all %>
	<%= f.submit %>
<% end %>

web-app/app/views/messages/edit.html.erb
<h1>Редактирование</h1>
<%= render "form" %>

web-app/app/views/messages/index.html.erb
<%= render partial: 'shared/list_messages.html.erb'%>

web-app/app/views/messages/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBRkajFk38d_24oT0mo8rkMWb1_fJHSMW8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<div class="row">

  <div class="col-md-6">
    <div clss="qwe">

    </div>


            <div class="panel-body">
              <div class="row">
                <div class="col-md-12">
                  <h3>
                    <p> <b><%= @message.body %></b> </p>

                  </h3>
                  <div class="row">
                    <div class="col-md-6">
                      <h3>
                        <p>Статус:
                          <b> <%= @message.status %></b></p>
                        <p>Категория:
                          <b><%= @message.category.title %></b></p>
                      </h3>
                    </div>

                    <div class="col-md-6">

                      <br>
                      <%= render partial: 'messages/change_status', locals: { message: @message } %>
                      <br>
                      <%= render partial: 'messages/change_category', locals: { message: @message } %>
                    </div>
                  </div>
                  <% @message.images.each do |image| %>

                    <%= link_to image_tag(image.image_url(:medium), class: 'problem_image img-rounded' ), "#modal-#{image.id}", "data-toggle" => "modal" %>
                    <div id="modal-<%= image.id %>" class="modal fade" role="dialog">
                      <div class="modal-dialog modal-lg">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><%= truncate(@message.body, :length => 50) %></h4>
                          </div>
                          <div class="modal-body">
                            <%= image_tag(image.image_url(:actual)) %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <hr>
                  <%= link_to 'Удалить сообщение', archiving_messages_path(@message), method: :post, class: 'btn btn-danger' %>
                </div>
              </div>

        </div>


  </div>
  <div class="col-md-6" style="display: flex; flex-direction: row; justify-content: space-between;">
    <div style='width: 585px;'>


      <h2><b><%= @message.address %></b></h2>

      <div id="map" style='width: 585px; height: 450px;'></div>

    </div>
  </div>

</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {mapTypeId: 'hybrid'}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>