web-app/config/routes.rb
Rails.application.routes.draw do
	root 'messages#index'
	TheRoleManagementPanel::Routes.mixin(self)
  devise_for :users, :controllers => { :invitations => 'invitations' }
  resources :users

  resources :categories, except: [:destroy] do
    collection do
      get :archived_categories, as: 'archived'
    end
    member do
      post :archiving
      post :unarchiving
    end
  end

  resources :messages do
    collection do
      post ':id/destroy' => 'messages#archiving', as: 'archiving'
    end
    resources :images, only: [:create]
  end
  post '/messages/:message_id/image' => 'messages#image_save'

  get '/rss' => 'rss#rss'
  get '/atom' => 'rss#atom'
end

web-app/app/models/category.rb
class Category < ApplicationRecord
	has_many :messages, dependent: :destroy

	validates :title, presence: true, length: {maximum: 40}


end

web-app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :role_required # проверяет роль юзера
  before_action :set_category, only: [:show, :edit, :update, :archiving, :unarchiving]

  def index
    @categories = Category.where(archived: false)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
      flash[:success] = "Категория успешно создана."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to root_path
      flash[:success] = "Категория успешно обновлена."
    else
      render 'edit'
      flash[:danger] = "Ошибка."
    end
  end

  def show
      if params[:status] == 'all'
        @messages = @category.messages
      else
        @messages = @category.messages.where(status: params[:status])
      end
  end

  def archiving
    @category.archived = true
    @category.save
    flash[:success] = "Категория успешно архивирована."
    redirect_to categories_path
  end

  def unarchiving
    @category.archived = false
    @category.save
    flash[:success] = "Категория успешно восстановлена."
    redirect_to categories_path
  end

  def archived_categories
    @categories = Category.where(archived: true)
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

web-app/app/helpers/categories_helper.rb
module CategoriesHelper
end

web-app/app/views/categories/_form.html.erb
<div class="col-sm-4">
	<%= simple_form_for(@category) do |f| %>
		<%= f.error_notification %>
		<%= f.input :title, label: 'Название', class: 'form-control' %>
		<%= f.submit "Создать", class: 'btn btn-success' %>
	<% end %>
</div>

web-app/app/views/categories/archived_categories.html.erb
<h1>Архивные категории</h1>
<table class="table">
	<tr>
		<th>Название</th>
		<th>Действия</th>
	</tr>

	<% @categories.each do |category| %>
		<tr>
			<td><%= category.title %></td>
			<td><%= link_to 'Восстановить', unarchiving_category_path(category), method: :post, id: "unarchiving_category_#{category.id}" %></td>
		</tr>
	<% end %>
</table>
<%= link_to "Показать все категории", categories_path %>

web-app/app/views/categories/edit.html.erb
<%= render 'form' %>

web-app/app/views/categories/index.html.erb
<h1>Категории</h1>
<table class="table">
	<tr>
		<th>Название</th>
		<th>Действия</th>
	</tr>

	<% @categories.each do |category| %>
		<tr>
			<td><%= link_to category.title, category_path(id: category.id, status: 'all'), id: "category_#{category.id}" %></td>
			<td><%= link_to 'Архивировать', archiving_category_path(category), method: :post, id: "archiving_category_#{category.id}" %></td>
			<td><%= link_to 'Обновить', edit_category_path(category), class: 'update', id: "edit_category_#{category.id}" %></td>
		</tr>
	<% end %>

</table>

<p><%= link_to "Добавить новую категорию", new_category_path, class: "btn btn-success" %></p>
<p><%= link_to "Показать архивные категории", archived_categories_path %></p>

web-app/app/views/categories/new.html.erb
<h2>Создать новую категорию</h2>
<hr>
<%= render 'form' %>

web-app/app/views/categories/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBRkajFk38d_24oT0mo8rkMWb1_fJHSMW8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<div class="row">
  <div class="col-md-12">
    <h2>
      <%= @title %>
    </h2>
    <hr />
  </div>
  <div class="col-md-6">
    <% @messages.each_with_index do |message, index| %>
      <div class="panel-group" role="tablist" aria-multiselectable="true">
        <div class="panel panel-<%= panel_type(message) %>">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" href="#collapse<%= index.to_s %>" aria-expanded="true" aria-controls="collapse<%= index.to_s %>">
                <%= truncate(message.body, :length => 50) %>
              </a>
            </h4>
          </div>
          <div id="collapse<%= index.to_s %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-12">
                  <h3>
                    <p> <b> Описание: </b> </p>
                    <p> <%= message.body %>  </p>
                    <hr>
                  </h3>
                  <div class="row">
                    <div class="col-md-6">
                      <h3>
                        <p>Статус:
                          <b> <%= message.status %></b></p>
                        <p>Категория:
                          <b><%= message.category.title %></b></p>
                      </h3>
                    </div>
                    <div class="col-md-6">
                      <br>
                      <%= render partial: 'messages/change_status', locals: { message: message } %>
                      <br>
                      <%= render partial: 'messages/change_category', locals: { message: message } %>
                    </div>
                  </div>
                  <% message.images.each do |image| %>
                    <hr>
                    <%= link_to image_tag(image.image_url(:medium), class: 'problem_image img-rounded' ), "#modal-#{image.id}", "data-toggle" => "modal" %>
                    <div id="modal-<%= image.id %>" class="modal fade" role="dialog">
                      <div class="modal-dialog modal-lg">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><%= truncate(message.body, :length => 50) %></h4>
                          </div>
                          <div class="modal-body">
                            <%= image_tag(image.image_url(:actual)) %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <hr>
                  <%= link_to 'Удалить сообщение', archiving_messages_path(message), method: :post, class: 'btn btn-danger' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <div style='width: 585px; position: fixed;'>
      <div class="btn-group btn-group-justified">
        <%= link_to "New", category_path(id: @category.id, status: 'new_message'), class: "btn btn-info" %>
        <%= link_to "Done", category_path(id: @category.id, status: 'done'), class: "btn btn-success" %>
        <%= link_to "All", category_path(id: @category.id, status: 'all'), class: "btn btn-primary" %>
        <%= link_to "Actual", category_path(id: @category.id, status: 'actual'), class: "btn btn-warning" %>
        <%= link_to "Not Relevant", category_path(id: @category.id, status: 'not_relevant'), class: "btn btn-default" %>
      </div>
      <hr>
      <div id="map" style='width: 585px; height: 450px;'></div>
    </div>
  </div>

</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {mapTypeId: 'hybrid'}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>